from enum import StrEnum


class IntentType(StrEnum):
    BUSINESS_QA = "BUSINESS_QA"
    LEAD_DISCOVERY = "LEAD_DISCOVERY"
    TASK_MODIFICATION = "TASK_MODIFICATION"
    LEAD_QUERY = "LEAD_QUERY"
    EXPORT_REQUEST = "EXPORT_REQUEST"
    GENERAL_CHAT = "GENERAL_CHAT"


class TaskStage(StrEnum):
    CREATED = "CREATED"
    COLLECTING_REQUIREMENTS = "COLLECTING_REQUIREMENTS"
    BUSINESS_PLANNING = "BUSINESS_PLANNING"
    DISCOVERY = "DISCOVERY"
    CHEAP_ENRICHMENT = "CHEAP_ENRICHMENT"
    DEEP_RESEARCH = "DEEP_RESEARCH"
    ENTITY_RESOLUTION = "ENTITY_RESOLUTION"
    VERIFICATION = "VERIFICATION"
    SCORING = "SCORING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TaskStatus(StrEnum):
    RUNNING = "RUNNING"
    WAITING_USER = "WAITING_USER"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class MutationScope(StrEnum):
    NONE = "NONE"
    DISPLAY_ONLY = "DISPLAY_ONLY"
    RANK_ONLY = "RANK_ONLY"
    FILTER_ONLY = "FILTER_ONLY"
    ENRICHMENT_REQUIRED = "ENRICHMENT_REQUIRED"
    DISCOVERY_REQUIRED = "DISCOVERY_REQUIRED"
    FULL_REPLAN = "FULL_REPLAN"
