from enum import StrEnum


class DocumentAuthority(StrEnum):
    OFFICIAL = "OFFICIAL"
    INTERNAL = "INTERNAL"
    MARKETING_EXPERIENCE = "MARKETING_EXPERIENCE"
    DEMO = "DEMO"


class DocumentStatus(StrEnum):
    UPLOADED = "UPLOADED"
    PARSING = "PARSING"
    INDEXING = "INDEXING"
    READY = "READY"
    FAILED = "FAILED"
    DISABLED = "DISABLED"


class ChunkType(StrEnum):
    PARAGRAPH = "PARAGRAPH"
    SECTION = "SECTION"
    TABLE = "TABLE"
    TABLE_ROW = "TABLE_ROW"


class KnowledgeFailure(StrEnum):
    INVALID_DOCUMENT = "INVALID_DOCUMENT"
    PDF_PARSE_FAILED = "PDF_PARSE_FAILED"
    EMBEDDING_FAILED = "EMBEDDING_FAILED"
    VECTOR_STORE_FAILED = "VECTOR_STORE_FAILED"
    SPARSE_RETRIEVAL_FAILED = "SPARSE_RETRIEVAL_FAILED"
    RERANK_FAILED = "RERANK_FAILED"
    LLM_FAILED = "LLM_FAILED"
    NO_EVIDENCE = "NO_EVIDENCE"
    CITATION_INVALID = "CITATION_INVALID"
