"""Add Phase 4 research persistence.

Revision ID: 0004_phase4_enterprise_research
Revises: 0003_phase3_rules_criteria
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004_phase4_enterprise_research"
down_revision = "0003_phase3_rules_criteria"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("research_search_plans", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("task_id", sa.String(80), nullable=False, index=True), sa.Column("criteria_snapshot_id", sa.UUID(), nullable=False, index=True), sa.Column("plan_json", postgresql.JSONB(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("research_runs", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("task_id", sa.String(80), nullable=False, index=True), sa.Column("criteria_snapshot_id", sa.UUID(), nullable=False, index=True), sa.Column("search_plan_id", sa.UUID()), sa.Column("status", sa.String(24), nullable=False), sa.Column("stage", sa.String(40), nullable=False), sa.Column("budget_json", postgresql.JSONB(), nullable=False), sa.Column("used_budget_json", postgresql.JSONB(), nullable=False), sa.Column("raw_candidate_set_id", sa.UUID()), sa.Column("cheap_enriched_set_id", sa.UUID()), sa.Column("filtered_candidate_set_id", sa.UUID()), sa.Column("researched_candidate_set_id", sa.UUID()), sa.Column("error_code", sa.String(80)), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("finished_at", sa.DateTime(timezone=True)))
    op.create_table("enterprise_candidates", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("research_run_id", sa.UUID(), sa.ForeignKey("research_runs.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("source_provider", sa.String(60), nullable=False), sa.Column("source_entity_id", sa.String(255)), sa.Column("source_name", sa.String(255), nullable=False), sa.Column("normalized_name", sa.String(255), nullable=False, index=True), sa.Column("provisional_json", postgresql.JSONB(), nullable=False), sa.Column("research_status", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("candidate_sets", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("research_run_id", sa.UUID(), sa.ForeignKey("research_runs.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("parent_set_id", sa.UUID(), sa.ForeignKey("candidate_sets.id")), sa.Column("stage", sa.String(40), nullable=False), sa.Column("criteria_snapshot_id", sa.UUID(), nullable=False, index=True), sa.Column("search_plan_id", sa.UUID(), nullable=False), sa.Column("candidate_count", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("candidate_set_members", sa.Column("candidate_set_id", sa.UUID(), sa.ForeignKey("candidate_sets.id", ondelete="CASCADE"), primary_key=True), sa.Column("candidate_id", sa.UUID(), sa.ForeignKey("enterprise_candidates.id", ondelete="CASCADE"), primary_key=True), sa.Column("position", sa.Integer(), nullable=False), sa.Column("selection_reason", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("research_source_records", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("research_run_id", sa.UUID(), sa.ForeignKey("research_runs.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("candidate_id", sa.UUID(), sa.ForeignKey("enterprise_candidates.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("provider", sa.String(60), nullable=False), sa.Column("source_type", sa.String(40), nullable=False), sa.Column("source_id", sa.String(255)), sa.Column("source_url", sa.Text()), sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False), sa.Column("payload_json", postgresql.JSONB()), sa.Column("content_text", sa.Text()), sa.Column("content_hash", sa.String(64)), sa.Column("http_status", sa.Integer()))
    op.create_table("tool_runs", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("research_run_id", sa.UUID(), sa.ForeignKey("research_runs.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("task_id", sa.String(80), nullable=False, index=True), sa.Column("query_id", sa.UUID()), sa.Column("tool_name", sa.String(80), nullable=False), sa.Column("provider", sa.String(60), nullable=False), sa.Column("request_hash", sa.String(64), nullable=False, unique=True, index=True), sa.Column("request_summary", postgresql.JSONB(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("latency_ms", sa.Integer(), nullable=False), sa.Column("retry_count", sa.Integer(), nullable=False), sa.Column("error_code", sa.String(80)), sa.Column("result_json", postgresql.JSONB()), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("research_batches", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("research_run_id", sa.UUID(), sa.ForeignKey("research_runs.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("stage", sa.String(40), nullable=False), sa.Column("batch_index", sa.Integer(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("candidate_ids", postgresql.JSONB(), nullable=False), sa.Column("query_ids", postgresql.JSONB(), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.Column("error_code", sa.String(80)))


def downgrade() -> None:
    for table in ("research_batches", "tool_runs", "research_source_records", "candidate_set_members", "candidate_sets", "enterprise_candidates", "research_runs", "research_search_plans"):
        op.drop_table(table)
