"""Add Phase 5 entity resolution, evidence verification and lead scoring.

Revision ID: 0005_phase5_entity_evidence_scoring
Revises: 0004_phase4_enterprise_research
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0005_phase5_entity_evidence_scoring"
down_revision = "0004_phase4_enterprise_research"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("entity_resolution_runs", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("task_id", sa.String(80), nullable=False, index=True), sa.Column("candidate_set_id", sa.UUID(), sa.ForeignKey("candidate_sets.id"), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("rule_version", sa.String(80), nullable=False), sa.Column("candidate_count", sa.Integer(), nullable=False), sa.Column("enterprise_count", sa.Integer(), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("finished_at", sa.DateTime(timezone=True)))
    op.create_table("canonical_enterprises", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("canonical_name", sa.String(255), nullable=False, index=True), sa.Column("entity_type", sa.String(32), nullable=False), sa.Column("parent_enterprise_id", sa.UUID(), sa.ForeignKey("canonical_enterprises.id")), sa.Column("unified_social_credit_code", sa.String(32), index=True), sa.Column("primary_region", sa.String(100)), sa.Column("primary_website", sa.Text()), sa.Column("resolution_status", sa.String(24), nullable=False), sa.Column("resolution_confidence", sa.Float(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("enterprise_candidate_links", sa.Column("enterprise_id", sa.UUID(), sa.ForeignKey("canonical_enterprises.id", ondelete="CASCADE"), primary_key=True), sa.Column("candidate_id", sa.UUID(), sa.ForeignKey("enterprise_candidates.id", ondelete="CASCADE"), primary_key=True), sa.Column("resolution_run_id", sa.UUID(), sa.ForeignKey("entity_resolution_runs.id"), nullable=False, index=True), sa.Column("decision", sa.String(32), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("entity_resolution_decisions", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("resolution_run_id", sa.UUID(), sa.ForeignKey("entity_resolution_runs.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("left_candidate_id", sa.UUID(), sa.ForeignKey("enterprise_candidates.id"), nullable=False), sa.Column("right_candidate_id", sa.UUID(), sa.ForeignKey("enterprise_candidates.id"), nullable=False), sa.Column("relation", sa.String(32), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("audit_json", postgresql.JSONB(), nullable=False))
    op.create_table("enterprise_relations", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("from_enterprise_id", sa.UUID(), sa.ForeignKey("canonical_enterprises.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("to_enterprise_id", sa.UUID(), sa.ForeignKey("canonical_enterprises.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("relation_type", sa.String(32), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("evidence_ids", postgresql.JSONB(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("enterprise_locations", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("enterprise_id", sa.UUID(), sa.ForeignKey("canonical_enterprises.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("location_type", sa.String(32), nullable=False), sa.Column("address", sa.Text(), nullable=False), sa.Column("normalized_address", sa.Text(), nullable=False), sa.Column("lat", sa.Float()), sa.Column("lng", sa.Float()), sa.Column("evidence_ids", postgresql.JSONB(), nullable=False), sa.Column("verification_status", sa.String(24), nullable=False))
    op.create_table("verification_runs", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("task_id", sa.String(80), nullable=False, index=True), sa.Column("candidate_set_id", sa.UUID(), sa.ForeignKey("candidate_sets.id"), nullable=False), sa.Column("resolution_run_id", sa.UUID(), sa.ForeignKey("entity_resolution_runs.id"), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("budget_json", postgresql.JSONB(), nullable=False), sa.Column("used_budget_json", postgresql.JSONB(), nullable=False), sa.Column("warnings", postgresql.JSONB(), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("finished_at", sa.DateTime(timezone=True)))
    op.create_table("enterprise_evidence", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("enterprise_id", sa.UUID(), sa.ForeignKey("canonical_enterprises.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("field_name", sa.String(100), nullable=False, index=True), sa.Column("value_json", postgresql.JSONB(), nullable=False), sa.Column("normalized_value_json", postgresql.JSONB()), sa.Column("provider", sa.String(60), nullable=False), sa.Column("source_type", sa.String(40), nullable=False), sa.Column("source_record_id", sa.UUID(), sa.ForeignKey("research_source_records.id"), nullable=False, index=True), sa.Column("source_url", sa.Text()), sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("extraction_method", sa.String(32), nullable=False), sa.Column("raw_reference", sa.Text()), sa.Column("stale", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("resolved_fields", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("verification_run_id", sa.UUID(), sa.ForeignKey("verification_runs.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("enterprise_id", sa.UUID(), sa.ForeignKey("canonical_enterprises.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("field_name", sa.String(100), nullable=False), sa.Column("primary_value_json", postgresql.JSONB()), sa.Column("status", sa.String(24), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("supporting_evidence_ids", postgresql.JSONB(), nullable=False), sa.Column("conflicting_evidence_ids", postgresql.JSONB(), nullable=False), sa.Column("alternatives", postgresql.JSONB(), nullable=False), sa.Column("selection_reason", sa.Text()), sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("verification_run_id", "enterprise_id", "field_name"))
    op.create_table("verified_enterprise_profiles", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("verification_run_id", sa.UUID(), sa.ForeignKey("verification_runs.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("enterprise_id", sa.UUID(), sa.ForeignKey("canonical_enterprises.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("profile_json", postgresql.JSONB(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("evidence_coverage", sa.Float(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("scoring_profiles", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("business_code", sa.String(80), nullable=False, index=True), sa.Column("version", sa.Integer(), nullable=False), sa.Column("profile_json", postgresql.JSONB(), nullable=False), sa.Column("active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("business_code", "version"))
    op.create_table("lead_scores", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("task_id", sa.String(80), nullable=False, index=True), sa.Column("enterprise_id", sa.UUID(), sa.ForeignKey("canonical_enterprises.id"), nullable=False, index=True), sa.Column("criteria_snapshot_id", sa.UUID(), sa.ForeignKey("lead_criteria_snapshots.id"), nullable=False), sa.Column("scoring_profile_id", sa.UUID(), sa.ForeignKey("scoring_profiles.id"), nullable=False), sa.Column("scoring_profile_version", sa.Integer(), nullable=False), sa.Column("total_score", sa.Float()), sa.Column("rank_status", sa.String(24), nullable=False), sa.Column("verification_status", sa.String(24), nullable=False), sa.Column("evidence_coverage", sa.Float(), nullable=False), sa.Column("component_scores", postgresql.JSONB(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("recommendation_reasons", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("lead_score_id", sa.UUID(), sa.ForeignKey("lead_scores.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("summary", sa.Text(), nullable=False), sa.Column("reason_codes", postgresql.JSONB(), nullable=False), sa.Column("evidence_ids", postgresql.JSONB(), nullable=False), sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("verified_lead_sets", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("task_id", sa.String(80), nullable=False, index=True), sa.Column("criteria_snapshot_id", sa.UUID(), sa.ForeignKey("lead_criteria_snapshots.id"), nullable=False), sa.Column("scoring_profile_id", sa.UUID(), sa.ForeignKey("scoring_profiles.id"), nullable=False), sa.Column("lead_ids", postgresql.JSONB(), nullable=False), sa.Column("lead_count", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))


def downgrade() -> None:
    for table in ("verified_lead_sets", "recommendation_reasons", "lead_scores", "scoring_profiles", "verified_enterprise_profiles", "resolved_fields", "enterprise_evidence", "verification_runs", "enterprise_locations", "enterprise_relations", "entity_resolution_decisions", "enterprise_candidate_links", "canonical_enterprises", "entity_resolution_runs"):
        op.drop_table(table)
