from enum import StrEnum


class EvidenceSourceType(StrEnum):
    OFFICIAL_WEBSITE = "OFFICIAL_WEBSITE"
    ENTERPRISE_DATABASE = "ENTERPRISE_DATABASE"
    MAP_POI = "MAP_POI"
    WEB_SEARCH = "WEB_SEARCH"
    PUBLIC_WEBPAGE = "PUBLIC_WEBPAGE"
    INTERNAL_DATABASE = "INTERNAL_DATABASE"


class FieldVerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    PARTIAL = "PARTIAL"
    CONFLICTING = "CONFLICTING"
    UNVERIFIED = "UNVERIFIED"
    MISSING = "MISSING"


class EnterpriseVerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    PARTIAL = "PARTIAL"
    CONFLICTING = "CONFLICTING"
    UNVERIFIED = "UNVERIFIED"


class Phase5FailureCode(StrEnum):
    ENTITY_RESOLUTION_FAILED = "ENTITY_RESOLUTION_FAILED"
    AMBIGUOUS_ENTITY = "AMBIGUOUS_ENTITY"
    EVIDENCE_EXTRACTION_FAILED = "EVIDENCE_EXTRACTION_FAILED"
    EVIDENCE_CONFLICT = "EVIDENCE_CONFLICT"
    FIELD_RESOLUTION_FAILED = "FIELD_RESOLUTION_FAILED"
    VERIFICATION_BUDGET_EXHAUSTED = "VERIFICATION_BUDGET_EXHAUSTED"
    PROFILE_BUILD_FAILED = "PROFILE_BUILD_FAILED"
    SCORING_PROFILE_MISSING = "SCORING_PROFILE_MISSING"
    LEAD_SCORING_FAILED = "LEAD_SCORING_FAILED"
    NOT_SCORABLE = "NOT_SCORABLE"
